name: Request PR Reviews

on:
  pull_request:
    types: [opened]

jobs:
  add_reviewers:
    name: Add App Reviewers
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add reviewers
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit $PR_URL --add-reviewer "github-copilot[bot]"